apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightrag-minimal.secretName" . }}
  labels:
    {{- include "lightrag-minimal.labels" . | nindent 4 }}
type: Opaque
data:
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | b64enc | quote }}